### ISSUE TITLE
Graphics for plugin

### ISSUE THREAD

**Issue by scottybo** [ClassicPress/ClassicPress-Migration-Plugin#1]
![classicpress-icon-blue-128](https://user-images.githubusercontent.com/11498904/44798335-19794200-aba9-11e8-9142-723d3c1bebd9.png)

![banner](https://user-images.githubusercontent.com/11498904/44798456-6eb55380-aba9-11e8-9d87-c9672d29b3f5.png)

**Comment by marctenax** [comment]
Yeah!

**Comment by ruiguerreiro79** [comment]
The new plugin banner and icon for the WordPress directory was added today.
