### ISSUE TITLE
Unblock PHP 8.0, block 8.1 and 8.2

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/ClassicPress-Migration-Plugin#101]
Since version 1.5.0 supports PHP 8.0 we should unblock it in migration plugin, which was supposed to be blocked in #87 

We should block 8.1, it seems migration plugin isn't blocking it right now as mentioned in the forum:
https://forums.classicpress.net/t/checking-jquery-functionality-with-cryout-serious-theme-settings-plugin/4448/4

We should also block 8.2 now.

**Comment by mattyrob** [comment]
This Issue was resolved with an update to the API endpoints:
https://github.com/ClassicPress/ClassicPress-APIs/pull/100
