### ISSUE TITLE
After plugin activation unclear about next step

### ISSUE THREAD

**Issue by senlin** [ClassicPress/ClassicPress-Migration-Plugin#13]
After the plugin has been activated it is not clear what to do next.

I would like to suggest to add a link to the switch page next to the Deactivation link.

Screenshot:
![migration-plugin-activated](https://user-images.githubusercontent.com/650066/47254058-3c5efe80-d454-11e8-8fc1-2c9c12b198fc.png)

**Comment by nylen** [comment]
Fixed in #15 and #16.
