### ISSUE TITLE
On Multisite Migration plugin does not seem to work

### ISSUE THREAD

**Issue by senlin** [ClassicPress/ClassicPress-Migration-Plugin#14]
Tried the plugin on local Multisite install and tried from both Network activated and single site activation.

It is not possible to update the entire network in one go either, is it?

Single site admin > Tools > Switch to ClassicPress > click Switch button

Result this screen (screenshot):
![migration-plugin-wpmu](https://user-images.githubusercontent.com/650066/47254121-6c5ad180-d455-11e8-8587-04204a611566.png)

**Comment by nylen** [comment]
Good question.  For now I'm planning to block the upgrade for multisite installs, but it sounds like there are bigger issues there (can't even get to the plugin page, because you don't have a Tools menu).

**Comment by senlin** [comment]
> can't even get to the plugin page, because you don't have a Tools menu

Well there is that, but also on per site activation it doesn't work (the screenshot I pasted is from that).

**Comment by nylen** [comment]
You should no longer see any change to the main WordPress updates screen due to this plugin, that was just an initial prototype version.

**Comment by nylen** [comment]
This is fixed now:

![2018-10-22t16 18 15-05 00](https://user-images.githubusercontent.com/227022/47320110-1aad7500-d616-11e8-9c1e-fca03860f05f.png)
