### ISSUE TITLE
Wrong link for "join our slack"

### ISSUE THREAD

**Issue by striebwj** [ClassicPress/ClassicPress-Migration-Plugin#20]
Re comment on [this commit](https://github.com/ClassicPress/ClassicPress-Migration-Plugin/commit/49c3243adabadcf38739054c6b40abfaba45a03b#commitcomment-31001485). 

The link to "join our slack" points to GitHub.

**Comment by nylen** [comment]
Copy/paste fail.  This was fixed in e5debe4fef3187f6efef96a1f2018ea91add00ee, thanks.
