### ISSUE TITLE
CI improvement: Docker image caching

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Migration-Plugin#23]
https://github.com/lando/lando/issues/1248

> we do cache the images using docker's image cache

> This seems like it may be helpful, so my question then becomes: how do I make Travis CI persist the docker image cache between builds?  Where does this cache live?
>
> Here are some resources that point to potential solutions:
>
> - https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-246302666
> - https://gist.github.com/hc2p/9e284cee3d585eefbc59454e44cc247a
> - https://stackoverflow.com/q/35305492/106302

**Comment by mattyrob** [comment]
Stale Issue now
