### ISSUE TITLE
CI improvement: Test on PHP 5.2

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Migration-Plugin#24]
https://github.com/lando/lando/issues/1256

> I don't think we're going to create a new docker image for a PHP version that old. It's a surprise we still have 5.3. There are various community docker images though that may work. We allow you to override default docker images for any service so you might just want to add in your own docker file that includes the customizations

> Reference: https://docs.devwithlando.io/config/advanced.html#using-dockerfiles

**Comment by Ugoku** [comment]
From https://www.classicpress.net/roadmap/ : 
> Support for PHP lower than 5.6 has been dropped

**Comment by nylen** [comment]
The benefit of testing against PHP 5.2 would not be for ClassicPress, but for WordPress sites still running on this version.  We would be making sure that our plugin doesn't throw a fatal error on PHP 5.2.

This is going to be unimportant pretty soon anyway though.  WordPress may also be bumping the minimum PHP version to 5.6 in a few months:  https://make.wordpress.org/core/2018/12/08/updating-the-minimum-php-version/

**Comment by nylen** [comment]
I haven't had reason to care about this since I created this issue, so I'm closing it.
