### ISSUE TITLE
Plugin conflict: WP Config File Editor

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Migration-Plugin#28]
> I had been playing around with 'WP Config File Editor' and forgot to deactivate it. I also had Wordfence activated prior and deactivated it as a precaution. But the plugin that was blocking it seems to have been the 'WP Config File Editor'. After that it was very quick migration.

**Comment by mattyrob** [comment]
This is fixed via the Plugin checks in the migration plugin and the update API endpoint
