### ISSUE TITLE
Support migration of multisite installs

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Migration-Plugin#29]
We've had some interest in migrating multisite installs, which we didn't get to for `0.1.0`.  Here is a potential starting point:

> When the multisite check is done, shouldn't it be possible to switch to using wp-admin/network/update-core.php instead of just wp-admin/update-core.php ?

Should the plugin be network activated, or is there no reason to make this a requirement?

`update_core` is probably still the right capability check to use, according to https://codex.wordpress.org/Roles_and_Capabilities#Additional_Admin_Capabilities.

We need to finish #12 first.

Also, this may end up being a non-issue, but I think multisite installs are more likely to be using customized paths, so this would be good to test too.

Anything else?

**Comment by nylen** [comment]
For multisites, the migration should probably be done from the network admin menu.  This means it should be network activated.

**Comment by nylen** [comment]
In the meantime, this seems to work with some manual code edits:

> I just changed the code for straight multisite from using the update-core.php to network/update-core.php and ran it. It worked perfectly. I didn't do a check for multisite. I just ran it with the presumption of multisite to see if it would work. It does. Of course, I commented out the check that stopped it being used on multisite.

**Comment by nylen** [comment]
We're using `current_user_can( 'update_core' )`, which in multisite will only be true for super admins.

**Comment by CPLouis** [comment]
Right.

**Comment by nylen** [comment]
Just a quick update - there is a PR open for this improvement that needs to be finished.  #32

**Comment by CPLouis** [comment]
I have worked on lib/admin-page.php. Don't know if it is of any value, given the desire to make multisite activation go to network menu. But it's here if anyone wants to take a look.
May be pretty sloppy, don't know. (I'm not a coder - officially)

[admin-page.zip](https://github.com/ClassicPress/ClassicPress-Migration-Plugin/files/2586980/admin-page.zip)

**Comment by CPLouis** [comment]
I believe I am very close to having the plugin compatible with the paramaters requested for multisite.

If multisite:
Requires Network activation.
Subsite plugins show "Network Only".
Once activated via Network, subsites no longer see the plugin.
Upgrade menu item in Network Admin.

If single site:
no change.

I should have more news soon.

**Comment by CPLouis** [comment]
Guess, I wasted my time.

**Comment by CPLouis** [comment]
I wish that were all that needed to be done. I guess if it were just that, someone else would have done it.
I don't know how to work with Github. Call me stupid, I just haven't needed it and haven't done a lot of coding.

However, since I hadn't seen anyone come up with anything I did it myself. I am happy to share my version. I just don't know how other than to upload the plugin right here. I don't want to cause a problem by doing that so, I will wait.

**Comment by nylen** [comment]
@CPLouis you can put all of your plugin files into a zip file and drop it into the comment box here. That won't cause any problems.

**Comment by CPLouis** [comment]
I have been dealing with a server issue arising from a DDoS attack the last several hours. It took the server down last night and then again this morning. I will be able to give more information on what I did with these files later. It basically, does what you were suggesting on the network activation and what I described above.
[ClassicPress-Migration-Plugin.zip](https://github.com/ClassicPress/ClassicPress-Migration-Plugin/files/2593405/ClassicPress-Migration-Plugin.zip)

**Comment by nylen** [comment]
This is finished!  If you have [docker](https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository) and [lando](https://docs.devwithlando.io/installation/installing.html) installed you can run `WP_MULTISITE=true ./test/lando-setup.sh` to spin up a multisite, which helps a lot with testing.

I did not use `Network: true` as described in [this article](http://strangework.com/2013/06/14/how-to-create-a-network-only-plugin-in-wordpress/), because we can do a bit better than that in terms of usability.

1. If you try to activate the plugin on a single site, you get a message pointing you in the right direction:

![2018-11-21t01 27 04-05 00](https://user-images.githubusercontent.com/227022/48822882-a22cf780-ed2c-11e8-8137-d2fef215764c.png)

2. If the plugin is network activated, and you have access, you can also get to the Upgrade page from the plugins page on individual sites.

Otherwise, the changes are basically as discussed here and on #32.

I'm going to close this and do a release shortly to go with ClassicPress `1.0.0-beta1`.  We are keeping the `beta` label though, so please let me know if you run into any issues!
