### ISSUE TITLE
"Upgrade" instead of "Switch" or "Migrate"

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Migration-Plugin#35]
fwolf [2:55 PM]
> as long as it works .. ie. WP 4.9.x, I am going to install and maintain it for clients. but I'm STRONGLY suggesting to upgrade to ClassicPress instead of having to endure to learn (and REWORK / REDESIGN) everything anew.

James Nylen [3:08 PM]
> Upgrade to ClassicPress!
> Maybe we should adopt that language in more places instead of migrate/switch.

Dick Metcalf [3:10 PM]
> ABSOLUTELY, James... and it IS an upgrade, no doubt about it... I'm very pleased, even with the ALPHA...

We can change this wording here in the plugin code, as well as on the [documentation page](https://docs.classicpress.net/installing-classicpress/#migrate-classicpress).  Are there any other places?

**Comment by striebwj** [comment]
You want to just change the wording not the functions, right?

**Comment by nylen** [comment]
I don't have a preference either way.  I think the important part is the messaging so just changing that would be fine by me.

**Comment by striebwj** [comment]
Submitted a PR (#36) with changes.

**Comment by nylen** [comment]
Done in #36.
