### ISSUE TITLE
Flawless migration success from WordPress to ClassicPress

### ISSUE THREAD

**Issue by stefanos82** [ClassicPress/ClassicPress-Migration-Plugin#40]
I have upgraded a fully custom WordPress website that I was scared to catch as I was working locally on it for weeks and it works 100%.

Well done! :100:

**Comment by nylen** [comment]
![aww-yeah](https://user-images.githubusercontent.com/227022/48636842-043ad500-e99a-11e8-8a61-6ccfae3dc1e8.gif)

Closing, as there is nothing to do here :)

**Comment by stefanos82** [comment]
Yeah, I just wanted to share my happiness, that's all ^_^
