### ISSUE TITLE
Cannot resolve github.com

### ISSUE THREAD

**Issue by Atari-Frosch** [ClassicPress/ClassicPress-Migration-Plugin#51]
This seems to be an odd one: I tried switching a blog that is not in use anymore, but has all WordPress stuff uptodate. Whatever I try, the plugin / tool keeps telling me:

`Herunterladen der Aktualisierung von https://github.com/ClassyBot/ClassicPress-nightly/releases/download/1.0.0-beta2%2Bmigration.20181220/ClassicPress-nightly-1.0.0-beta2-migration.20181220.zip …

Download fehlgeschlagen.: cURL error 6: Could not resolve host: github.com

Die Installation ging schief`

The host uses the nameservers of the host provider, which is Hetzner (213.133.99.99), and this nameserver DOES resolve github.com correctly. The IPs of github.com are also not in the iptables list of this host.

Additionally I tried a „git clone“ from the console of the same host on that file and got this error message:

# git clone https://github.com/ClassyBot/ClassicPress-nightly/releases/download/1.0.0-beta2%2Bmigration.20181220/ClassicPress-nightly-1.0.0-beta2-migration.20181220.zip
Klone nach 'ClassicPress-nightly-1.0.0-beta2-migration.20181220.zip' ...
remote: Not Found
fatal: repository 'https://github.com/ClassyBot/ClassicPress-nightly/releases/download/1.0.0-beta2%2Bmigration.20181220/ClassicPress-nightly-1.0.0-beta2-migration.20181220.zip/' not found

Friend of mine tried this git clone line on another host and got the same message.

I tried to find out whether the plugin tells curl to use another name server, and couldn't find anything like that. So, what is the problem?

**Comment by scottybo** [comment]
Thank you for the detailed report - a lot of our volunteers are on holiday at the moment, but I'm sure you'll get a response soon

**Comment by octoxan** [comment]
The url https://github.com/ClassyBot/ClassicPress-nightly/releases/download/1.0.0-beta2%2Bmigration.20181220/ClassicPress-nightly-1.0.0-beta2-migration.20181220.zip is a zip contained in the repo, and not the repo itself, so a git clone of that will always fail.

Can you try the following command in a test directory on the server:
```shell
curl -LO https://github.com/ClassyBot/ClassicPress-nightly/releases/download/1.0.0-beta2%2Bmigration.20181220/ClassicPress-nightly-1.0.0-beta2-migration.20181220.zip
```

If that fails, what's the output when you try `ping github.com` from the server?

**Comment by Atari-Frosch** [comment]
This curl command worked, and I got the file. But that is not where the tool expects it, I guess.
WordPress offers me the update to ClassicPress, to exactly this nightly version, but still fails to get the zip file, with the same error message as before.

**Comment by nylen** [comment]
@Atari-Frosch sorry for the delayed reply, but this is ultimately a problem with the server where WordPress is running.

Trying `curl` was a good troubleshooting effort, but it would have provided more info if it had failed.

You could do a [manual migration to ClassicPress](https://docs.classicpress.net/installing-classicpress/#migrating-to-classicpress-without-using-the-plugin), but then you'd most likely have the same issue when it comes time to update ClassicPress, so this really needs to be fixed on the server.

We could add a pre-migration check for this broken condition, but honestly I am hesitant to do that until a couple more people have reported this issue.  So far this is the only case.

**Comment by nylen** [comment]
Closing, this is a very rare problem with server configuration.  If anyone else is experiencing this issue, here are a few suggestions:

- Make sure there are no "firewall" type plugins or services installed that might be blocking a connection to github.com.  Blocking _outgoing_ connections in this manner is theoretically possible but not something I have seen before.
- Contact your hosting provider for help.
- Move to a different host.
