### ISSUE TITLE
Updating it to be compatible with WordPress 5.2?

### ISSUE THREAD

**Issue by seanking2919** [ClassicPress/ClassicPress-Migration-Plugin#58]
Hi guys,

So I just noticed that when I installed the ClassicPress migration that it's not yet compatible with the latest release, WordPress 5.2. See screenshot here: https://pic8.co/sh/eVtSSn.PNG

**Comment by nylen** [comment]
Hi @seanking2919, thanks for reporting this issue!

We needed to test migration from WordPress 5.2 and 5.2.1 first, but I've done that and enabled it for everyone in https://github.com/ClassicPress/ClassicPress-APIs/commit/44e43150716d70e7d07e505127f3d7407dfa7f35.

For future reference there is also a filter you can use to try the migration anyway: https://github.com/ClassicPress/ClassicPress-Migration-Plugin#how-can-i-use-this-plugin-with-an-unsupported-version-of-wordpress
