### ISSUE TITLE
Bump version support for WP 5.3

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress-Migration-Plugin#66]
I confirm having tested the plugin with the manual override and successfully migrated sites from WP 5.3.0 to CP

![Screenshot 2019-12-18 at 18 05 11](https://user-images.githubusercontent.com/7713923/71442998-8f4bda00-2719-11ea-9299-446c7e6af9ec.png)

I have checked the site runs well. Links are not broken. Content is fine across website. Apart from the need to bump to 1.1.2. On bumping to 1.1.2. All is well

![Screenshot 2019-12-18 at 18 04 37](https://user-images.githubusercontent.com/7713923/71442999-8fe47080-2719-11ea-8dc7-1d4cf5c64677.png)

**Comment by nylen** [comment]
Migration from WP up to 5.3.2 is enabled now.
