### ISSUE TITLE
Disable migration for WordPress.com sites

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-Migration-Plugin#7]
WordPress.com Business sites allow installing plugins, but we need to make sure the migration plugin doesn't run on these sites. This would be all kinds of bad, if it is even allowed by file permissions / other filter code (probably not).

For these sites, we should show a message to the effect of "Sorry, you must be running WordPress on a self-hosted site to use this plugin."

Are there other hosting platforms that we should detect and handle the same way?

**Comment by glagonikas** [comment]
I'd imagine any service offering hosted WP would need to be excluded. Some examples would be 1and1, GoDaddy, Bluehost, Dreamhost, SiteGround, HostGator etc.

Also, WP can be installed automatically via WHM/cPanel using Softaculous, Installatron, fantastico and possibly more. When a new WP is released, they either update the site automatically, or notify the admins. This is obviously not ideal as you don't want them to overwrite CP.

**Comment by nylen** [comment]
It depends on how each of those services do upgrades.  Unfortunately we will need to understand and test each one, and I only know the answer for WP.com.

I think cPanel just installs WP and lets the WP upgrade process do its thing, though, so we should be fine there.

This issue is specifically for WordPress.com and will be closed soon - I'd suggest opening a new one for each hosting provider we are concerned about.

**Comment by nylen** [comment]
This is implemented:

![2018-10-22t16 30 36-05 00](https://user-images.githubusercontent.com/227022/47320712-da4ef680-d617-11e8-9cc5-326a758179cd.png)
