### ISSUE TITLE
Migration Plugin Check for Software incompatible with CP is checking against a hardcoded list of items.

### ISSUE THREAD

**Issue by TukuToi** [ClassicPress/ClassicPress-Migration-Plugin#77]
Sorry to be late with this test.

I installed Migration Plugin last release on a WP 5.8 install to write a blogpost about it.

1. It correctly recognised WP Version
2. It correctly recognised Theme version
3. It incorrectly stated I do not run any known incompatible plugins, however I run Plugins that do not even declare minimal version.

As outlined [here](https://github.com/ClassicPress/ClassicPress-Migration-Plugin/issues/73#issuecomment-893317681) and [here](https://github.com/ClassicPress/ClassicPress-Migration-Plugin/issues/73#issuecomment-893317681):
>If that is below or equal to 4.9 we are good, **if not (no matter if empty, or above)** we should throw a warning.
 
This is important because too many themes and plugins simply do not give a 💩 about this, and totally _remove_ the readme tag.
This is especially the case in PRO software, they never need to pass any WP Plugin or Theme Check.
But even in software hosted on WP Repo this is the case sometimes. The tag is not mandatory, after all.

And if it is not there, we should throw a warning, that we do not know if there's some software not supporting CP, because right now, we assume that no tag means good to go, which is not the case.

I think the messages should be:
**For when we find plugins or themes without the tag**
> We are not aware that any of your active plugins are incompatible with ClassicPress. However note that you run some plugins/themes not adhering to the best practices.

**For when we find no plugins or themes without the tag**
> We are not aware that any of your active plugins are incompatible with ClassicPress. All your plugins and themes state to support WordPress 4.9, and thus should work just fine on ClassicPress. However, there is still a chance there'll be issues which is out of our hands to know. Make through tests.

**For when we find conflicting software**
> Current message is good.

**Comment by TukuToi** [comment]
Also there are those plugins that do not include a `readme.txt`. In those cases we should as well warn like shown above with same message.
Note, these are not random plugins (major players like PRO plugins actually do this, because as said, they never got warned as they never pass any WP Plugin or Theme Check).

**Comment by TukuToi** [comment]
Finally, I think it doesnt work.
I switched one of my plugin's readme to 5.0.0 minimal requirement and it didn't warn me.

I checked the code and it doesnt seem we actually scan the plugins on the site at all, we just check the remote API for a maybe existing parameter `plugins`, which is confusing me, because that mens we'd have to maintain some remote list of incompatible software (same with the themes).
That also means we can't really detect potentially incompatible software dynamically but need to hardcode the list somewhere, which is unmaintainable.

Perhaps I am missing something - however clearly it doesnt check existing plugin declarations, which I think would be the best way to do this.

**Comment by TukuToi** [comment]
Disregard all above.

The problem is simple.
We check against https://api-v1.classicpress.net/migration/ if there is any theme or plugin listed on that API currently installed.
That is wrong. Literally it will become impossible to maintain something like this as soon there are more than maybe 10 theme and plugins on that list.

Who will update that list? Based on what information? 

As said in the other 2 Git issue comments, we should try to read the readme.

In this sequence:
- Attempt to find the readme. 
- If not found, throw warning
- If found, attempt to read `Requires at least`
- If not found, throw notice
- If found, attempt to read version and act accordingly.

This is the only way going forward that allows us to almost 100% safely detect incompatible or potentially incompatible software without having a _huge_ work maintaining a list (and explaining to people _why_ a plugin that is actually compatible with CP versions, is listed as "not compatible" (like WordFence).

**Comment by TukuToi** [comment]
There are actually inbuilt functions we can re-use for our own purpose. Of course, we will have to rewrite the function a bit, but it will do the job just fine.

1. For themes: https://developer.wordpress.org/reference/functions/validate_theme_requirements/
2. For plugins: https://developer.wordpress.org/reference/functions/validate_plugin_requirements/

In short, we will foreach over each found plugin in the install, then [`get_plugin_data`](https://developer.wordpress.org/reference/functions/get_plugin_data/) and check against the minimal req we have.

For themes, we use [`wp_get_theme`](https://developer.wordpress.org/reference/functions/wp_get_theme/) and do the same.

Then, based on that information/result, we build the response.

**Comment by TukuToi** [comment]
This ugly code does what I mean:
```
function check_plugins_and_themes() {
	
	$plugins = get_plugins( );
	foreach ( $plugins as $plugin_slug => $plugin_array ) {
		if( ! isset( $plugin_array['RequiresWP'] ) || empty( $plugin_array['RequiresWP'] ) ){
			$incompatible_things[ $plugin_slug ] = $plugin_array['RequiresWP'];
		} elseif ( version_compare( $plugin_array['RequiresWP'], '4.9' ) >= 0  ) {
			$incompatible_things[ $plugin_slug ] = $plugin_array['RequiresWP'];
		} else {
			$incompatible_things[ $plugin_slug ] = $plugin_array['RequiresWP'];
		}
	}
	$themes = wp_get_themes();
	foreach ( $themes as $theme_slug => $theme_object ) {
		if( ! empty( $theme_object->get( 'RequiresWP' ) ) ){
			$incompatible_things[ $theme_slug ] = $theme_object->get( 'RequiresWP' );
		} elseif ( version_compare( $plugin_array['RequiresWP'], '4.9' ) >= 0  ) {
			$incompatible_things[ $theme_slug ] = $theme_object->get( 'RequiresWP' );
		} else {
			$incompatible_things[ $theme_slug ] = $theme_object->get( 'RequiresWP' );
		}
	}

	error_log( print_r( $incompatible_things , true ) );
}
```

There is one problem with this. Almost no plugin follows the best practices and available tags from https://developer.wordpress.org/plugins/plugin-basics/header-requirements/

Thus, we almost never have a required version in the Plugin header (php file, not readme).
This would need some more work, but already gives much more info than the remote API call, also because we can even check PHP version with this method.

Above would currently output something like this:
```
[06-Aug-2021 02:58:20 UTC] Array
(
    [switch-to-classicpress/switch-to-classicpress.php] => 
    [types/wpcf.php] => 
    [wp-views/wp-views.php] => 5.0
    [wporg-cli/wporg-cli.php] => 
    [phpdoc-parser/plugin.php] => 
    [cpnet-developer] => 
    [twentynineteen] => 4.9.6
    [twentytwenty] => 4.7
    [twentytwentyone] => 5.3
)
```

And yes, ClassicPress Migration plugin should make sure to add its supported version to the plugin file, it is missing, and that would put itself on the list.

I am running out of time for today, but I will proceed on this asap and also investigate ways to make it more thorough.

**Comment by TukuToi** [comment]
Changes are implemented [here](https://github.com/TukuToi/ClassicPress-Migration-Plugin/commit/f9a17773bae3aa410921ebc650172f41f3e7cd82) and [here](https://github.com/TukuToi/ClassicPress-Migration-Plugin/commit/c5a747495d1f2f1c96e2ff9806f869c37d4e6d39)

While at it I also fixed most of the WPCS issues I could fix. 
What is missing is the scan for the readme.txt file (if no version found in the main files or style files)
Not sure what the best approach is to that.

**Comment by joyously** [comment]
Why bother with the readme file? It should be checking the plugin header or theme style. 
As I mentioned in other places, the readme is only for the WP repository API. Core does not ever look at it since not all plugins or themes are from the repo.
The functions you linked were added in WP 5.5, although WP was checking the minimum WP version before those functions were added for plugin auto-updates. I suggested elsewhere that these should be added to core CP. 
Since there are so many plugins and themes without the field, a missing field can be interpreted differently than in WP if needed. Perhaps a warning or deactivation, but not a complete roadblock to migration.

**Comment by TukuToi** [comment]
All functions I used exist since way longer than WP 5.5
But I see now why so many plugins do not feature the `Requires at least`:
Only 5.3 added Added support for Requires at least and Requires PHP headers (see get_plugin_data)

However that is not the case for Themes. They always could and where supposed to pass this data to the style.css from which then the Theme object is built.

As I explain above, 99% of all themes and plugins only follow the readme.txt completeness because that is what gets reviewed by the WP Reviewers and that is what shows their data in the WordPress Repo.
Thus, the style.css and the plugin main file headers get neglected.

That leads us to the only chance we have:
Scan the files.

If we want to flag 99% of all plugins (even ClassicPress Migration itself was affected by this until I corrected it, and all plugins on the CP directory are as well affected by this) - then we need to scan those files.

**Comment by TukuToi** [comment]
That does not change the _fact_ that 99% of all theme and plugins do _not_ state the version in the files the functions actually look for.
Thus, we need to scan those files, if we want a real and complete check.

I can change the code to say "if empty, pass as compatible".
And then, plugins like toolset, or others - will pass as compatible, and then, sites will crash with fatal errors

And a handcrafted remote list like we have now would solve that, but it means to manually maintain a list. Which is not scalable.
Thus the only solution I still see that allows for _more, not complete but more complete_ check is... scan both places.

I think we win more if we do the effort and scan the read me too.
If then the plugin still doesn't "alarm", ew can say "we found nothing but it might still be that... or something like that

I guess there is no perfect solution, because in the end a plugin can even miss both declarations (as it is the case for example in WordPress Types plugin)

I just think the more we check, the safer we are. In the end, it is a little effort that makes the migration smoother.

**Comment by mattyrob** [comment]
There is now a PR for adding WordPress version checks for themes.

I'm reluctant to add it to plugins are broad usage of that header in plugins just isn't happening and we may well scare migrators off with too many warnings.

We can add plenty more known incompatible plugins to the migration API endpoint if we can be given the plugin slug.

**Comment by TukuToi** [comment]
OK great, I will ditch the fork I made as it would be obsolete.
I just realised this:
https://api.wordpress.org/plugins/info/1.0/tkt-maintenance

Most plugins we check against are on that API, and that API will always feature the ""requires";s:3:"4.9"" (example) prop.

@mattyrob - anything speaking against using that?
And if so, let me know if I should create the code or if you want to ( before I again duplicate work :P )
This way, we could have our manually curated list, and the remote one by WP API that checks the generic requirements.
If the plugin is on our list, we still can warn, as then there are "ulterior reasons" that may be independent from the version required.

**Comment by joyously** [comment]
There is this https://wpseek.com/pluginfilecheck/ which might have an interface.

**Comment by mattyrob** [comment]
@TukuToi - as far as I can tell the WordPress API simply serves a required version as pulled from the plugin files. The `get_plugin_data` function was extended to include `RequiresWP` in version 5.3.

I think adding reliance on a WordPress API endpoint should, wherever possible, be avoided. So perhaps we can look at directly leveraging the `get_file_data` function or back porting changes to the `get_plugin_data` function to look for the header entry locally - that would probably be after than multiple API calls too.

**Comment by TukuToi** [comment]
The problem isn’t really the code
The problem is more that almost no plugin has the info in the main file which is where the code looks

the api solves that by reading the readme file

but also right, another call to another api means more time consumed

**Comment by joyously** [comment]
The ultimate problem IS the code.
There is no guarantee that the readme has the field either because not all plugins are in the WP repo. I agree that we are better off not calling the WP API.

There is a WP function that you can easily use to slurp the readme, but I don't think it's good to rely on the file specifically made for the WP repo. 
You can read about the first time I suggested using it here: https://core.trac.wordpress.org/ticket/43992#comment:26

**Comment by TukuToi** [comment]
Thanks

Do let me know if I can help with this by writing the code for it or testing the plugin or else contributing to this repo.

**Comment by mattyrob** [comment]
I've created a PR that adds a step that scans plugin headers, works in my local testing if I add `Requires at least: 5.5` to the `hello.php` plugin header, for example.

https://github.com/ClassicPress/ClassicPress-Migration-Plugin/pull/83

**Comment by TukuToi** [comment]
Cool 
Do you think we can also add the readme check?
Since you’re using get_file_data, I think the convo Joy mentioned above could do the trick for that as well.
Then we’d be 99% covered

**Comment by mattyrob** [comment]
@TukuToi - What are we looking for in the ReadMe? It seems looking at WordPress documentation that the plugin headers is where you specify minimum required version and the ReadMe is where the tested / supported version if specified - so they're kind of opposites.

https://developer.wordpress.org/plugins/plugin-basics/header-requirements/
https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/

**Comment by nylen** [comment]
> we may well scare migrators off with too many warnings

I commented to this effect on the two PRs related to the new plugin/theme checks, but I think having more warnings over time is correct. The fact is that migration is getting more risky over time, as plugins, themes, and WP itself diverge farther from what ClassicPress can support.

**Comment by joyously** [comment]
_Is it checking only active plugins?_
_Can it deactivate the troublesome ones?_

**Comment by TukuToi** [comment]
We must check the readme because that’s the only place 99% of ALL plugins declare their requirements - same for themes 

Yes it checks of course only active plugin and theme.
Yo, we don’t deactivate things.
We’re not invading the users decisions.
A simple test of the plugin would btw answer this question as well.

We do not need or get more warnings by reading the readme, but _less_. Way way less.
Right now as said even your own plugin will mark itself as incompatible- just check my fork where I made all required changes already (version requirement and the code to read the file - but it misses the readme scan)

**Comment by mattyrob** [comment]
@TukuToi 

In the REadMe, unless I am missing your point, the header line is `Tested up to:` - so my understanding of that header in the ReadMe is that the plugin Author has tested up to that version - in my mind that does not rule out that it will work just fine on lower versions.

So, first question - it that the header you are proposing we utilise somehow, or something else.
And second question, if we use that header, what are we going to do with it? If it says Tested up to 5.8 how does that help us assess if the plugin works with ClassicPress any better than if it says 5.0 for example?

**Comment by TukuToi** [comment]
No, in the readme it is the same as in the plugin file: `Requires at least`

The thing is, yes - _it is wrong_
But the thing is also, that all plugins do it wrong.

You can browse WP repo to check, but see here the "model baby" of WP:
Readme file: https://plugins.trac.wordpress.org/browser/hello-dolly/tags/1.7.2/readme.txt (Features `Requires at least: 4.6`)
Main file: https://plugins.trac.wordpress.org/browser/hello-dolly/tags/1.7.2/hello.php (features nothing)

And that is the same throughout hundreds, thousands of plugins - whether new, old or else.
Same for Themes.
They are _supposed_ to put that data in style.css and do not. It's all in the readme.

Why?
Because WP Repo reads the readme. That is what will show on the repo. Thus no one ever checks the main plugin file
I had a discussion with some (in)famous WP iconic person and he stated " it is pretty clear how it has to be " upon my ask _why it is such as mess_
Also, they are fully aware of this, and actually _starting now_. read from the main plugin file. But, they wont go and ask developers to change existing plugins. Because there are literally over 50k plugins coded like the above example.

**Comment by joyously** [comment]
> Because WP Repo reads the readme. That is what will show on the repo. Thus no one ever checks the main plugin file

This isn't quite accurate. WP did not check for versions until very recently, so no old plugin or theme had it in the header. Themes were expected to ensure they did not cause a fatal, and plugins often do the same thing. Once WP was checking (because of auto-updates), there was no reason to change existing code and make it fail on older versions of WP.
The field is only needed for WP 5.3+ and only if the code has a requirement. If it runs on any version, no need to put the field there.

Relying on developers to put a version is fragile, which is why I pointed out the wpseek tool. There is also WP Tide which is supposed to be doing this sort of thing.

**Comment by TukuToi** [comment]
Fact is, _no plugin has that information in the header_
I am not going to discuss what is more accurate.

Sorry the assumption that it was because WP read the readme file, which it does, and which _is_ a fact.
When they implemented main plugin file headers is of no importance here. The facts are, and they show that Otto himself added the Requires at least: to the hello dolly just before 5.3 was released.
Why was it not updated accordingly just after 5.3?
because... WP does not read the main file.
It reads the text file.

Again - for our case here it matters nothing
For what matters they could have added support for out 100 years ago and still no plugin would feature it, leaving us with the same situation was we had at the begin of this Thread.
:)

**Comment by joyously** [comment]
>  (neither do themes)

Mine does, since before 5.3 because I knew it was coming.
> Why was it not updated accordingly just after 5.3?
because... WP does not read the main file.
It reads the text file.

No, because the plugin doesn't actually require a version, and was being used as an example.
And WP does read the main file, not the readme (although Andy had that in there as a fallback, it is removed in 5.8).

I still think the version check functions should be added to CP (backport the WP 5.3 code and recent fix, and add something for CP version) and the migration plugin should use that.
I don't know that wpseek could be used, as it would take time, but it already does the scan of code to arrive at a minimum version. It uses the REST API for the WP docs site, so now that we have a docs site like that, we could do similar (or is CP REST API sufficient?)

**Comment by TukuToi** [comment]
> Mine does, since before 5.3 because I knew it was coming.

That’s cool!
There’s 50k other plugins who don’t.

i don’t think writing 10 lines of code versus backporting a recent wp implementation is reasonable

**Comment by mattyrob** [comment]
I think we can implement code to check the plugin file AND the readme.

But we need to consider the name format for the readme, so is readme.txt === ReadMe.txt === readme.md for example.

Also, if we detect a `Requires at least:` in the plugin header and if the readme and they are different, which are we going to use, the highest? Lowest, or select a location? (My preference here is the highest given that we are trying to warn users migrating to WordPress that there may be issues).

**Comment by TukuToi** [comment]
I’d choose readme over main file just because if there’s 2 entries the readme is likely to be the “real” one.
But highest sounds good to me to.
Safer approach.

In wp, all readme files will be .txt
Thus I’d not even consider the .md case.
But if it’s not extremely complex why not.

about camel case situation, I didn’t check in depth how get file data works. If it’s case sensitive we should probably somehow get all possible cases (all lowercase and canelcase and all uppercase) but I haven’t seen this actually. Most are lowercase readme.txt

I can scan a few more plugins if it’s needed and feedback what patterns i find for example in every 10th of the most popular 100 plugins or so.
That should give us a pretty accurate stat.

Please let me know. 
(can’t we scan/get files no matter the letter case?)

**Comment by mattyrob** [comment]
Here is what I have so far:
```
$plugins = get_option( 'active_plugins' );
$plugin_headers = array( 'Name' => 'Plugin Name', 'RequiresWP'  => 'Requires at least' );
$declared_incompatible_plugins = array();

// Start by checking if plugins have declared they require WordPress 5.0 or higher
foreach ( $plugins as $plugin ) {
	$plugin_data = get_file_data( WP_PLUGIN_DIR . '/' . $plugin, $plugin_headers );
	if ( version_compare( $plugin_data['RequiresWP'], '5.0' ) >= 0 ) {
		$declared_incompatible_plugins[ $plugin ] = $plugin_data['Name'];
	} else {
		$plugin_files = get_plugin_files( $plugin );
		$readmes = array_filter( $plugin_files, function( $el ) {
			return ( stripos( $el, 'readme') !== false );
		} );
		foreach( $readmes as $readme ) {
			if ( empty( $readme ) ) {
				continue;
			}
			$readme_data = get_file_data( WP_PLUGIN_DIR . '/' . $readme, $plugin_headers );
			if ( version_compare( $readme_data['RequiresWP'], '5.0' ) >= 0 ) {
				$declared_incompatible_plugins[ $plugin ] = $plugin_data['Name'];
			}
		}
	}
}
```

Precedence isn't really and issue are we are look for either the plugin or readme to declare a higher requirement for WordPress. So, I'm checking the plugin header and if that is above 4.9 add to an array, if not then check the readme and if that's above 4.9 add it to the readme now.

The only additional code we need now is to warn the user if the header is missing in both files.

**Comment by mattyrob** [comment]
Have a check of the updated PR here:
https://github.com/ClassicPress/ClassicPress-Migration-Plugin/pull/83

**Comment by TukuToi** [comment]
I downloaded and tested

It checks both files, and both checks work, but there are some issues.

When the .md file declares requirement but the other 2 files not, the "found incompatible" message correctly displays, however we then still display this:
>We have detected one or more plugins that fail to declare a minimum compatible WordPress version. They may prevent or impact on migrating your site to ClassicPress.
>We would recommned deactivating the following plugins if you wish to continue migrating your site to ClassicPress:
>(list)

This is wrong, because if we find at least one tag presence, we can use it and do not need to make the warning.

---

I also saw some weird issue with the same plugin being listed 3 times in the "We have detected one or more incompatible plugins that prevent migrating your site to ClassicPress." list.
**This seems to happen when the plugin is on our remote API List.**

---

Additionally, again when the plugin is on the remote api list, _and it does not declare any requirement in its files_, then it gets added to the "We have detected one or more plugins that fail to declare a minimum compatible WordPress version." list
This is technically expected but wrong because if a plugin _is_ on our API list, it has to be marked as incompatible _no matter what_ and not listed anywhere else.

---

It seems additionally to that, if the plugin is on our repo, we do scan their main PHP file, but we do not scan their .txt file.
Here the right thing to _not scan anything at all_ when the plugin is on our API. We can simply skip all scanning in that case.

---

Thus the priority should be:
1. Is it on our repo? 
- if so, skip next and announce incompatible 
2. Not in the repo, does it have tag readme.txt file (consider camelcase and all uppercase and all lowercase)? 
- if so, skip next and announce incompatible
3. No tag in readme.txt file, does it have the tag in main plugin file?
- if so, skip next and announce incompatible
4. No tag in the main plugin file either, does it have the tag in readme.md plugin file?
- if so, skip next and announce incompatible
: else
state "We have detected one or more plugins that fail to declare a minimum compatible WordPress version."

---

I did not test Themes check.
@joyously want to give it a test run with themes?
You'd need to test by having a theme that uses style.css information, readme.txt information and also using twenty twenty-one and manually declare support for WP 4.9 in it, to see if that breaks the check or correctly pulls from remote.

**Comment by mattyrob** [comment]
I've tried to fix some of this (hopefully all) with some modifications. Running short of time now though so I've committed what I had for further testing.

**Comment by TukuToi** [comment]
It is better now, thou still something off with the ones on the remote api.
`types-access/types-access.php`, which is on the api list, is not shown at all as incompatible.
`types/wpcf.php` instead is shown twice.

The rest works great (related to Plugins). 

---

Themes 
I have installed and activated 2020 theme and changed its required statement in style.css to 5.1 but the tool still told me "It looks like you are using the Twenty Twenty theme. We are not aware of any incompatibilities between this theme and ClassicPress."
I then changed the statement in readme.txt and it also did not tell me it is incompatible.
I then changed to theme 2021 which was flagged as incompatible, and changing its minimal requirements in the style or/and readme did not make any difference.

So it seems like for themes we only scan remote repo as of now, which has one theme listed (but there are many themes not working by design with CP)

**Comment by mattyrob** [comment]
@TukuToi - I've just pushed a fix that should correct the issue with the display of plugin names from the API conflict list.

As for Themes, apologies if you've spent a lot of time on that but I've been focussing on the plugin checks thus far, I have not been looking at the Theme checking just yet.

**Comment by TukuToi** [comment]
No problem, I will test plugins asap again. Might be tomorrow for me thou (around 12 hours from now)

**Comment by mattyrob** [comment]
I have started extending the Theme checks but that's in another branch of the code, early changes here:
https://github.com/ClassicPress/ClassicPress-Migration-Plugin/pull/76
But it may need extending to check the readme files in a similar way to the plugin changes we've been iterating through.

**Comment by joyously** [comment]
_This is why I suggested to put the version checks into core (like WP did), so they could be used in multiple places._

**Comment by mattyrob** [comment]
@joyously - As far as I can tell the WordPress code changes only applied to Plugins and the plugin header is read with the readme as a fallback in WP - so there is a precedence. I may be wrong here and will try to look further.

For migration we would probably want a 'worst case' scenario though.

What other use cases can you foresee? And then perhaps we need to have a debate in the core slack channel to reach a decision on how to progress this.

**Comment by joyously** [comment]
> As far as I can tell the WordPress code changes only applied to Plugins

No, it's themes also. The new functions were made for the auto-update feature added in WP 5.5.
> the plugin header is read with the readme as a fallback in WP

It _was_, but the readme fallback was removed in WP 5.8 to clean things up from the confusion. I don't have a problem with using the fallback for migration.

> What other use cases can you foresee?

Any time it's best to have just one implementation, it should be in core (especially if core uses it). So auto-updates, a plugin like this one (migration), a plugin for remote managing a site, interfacing with a CLI, plugins doing their own updating especially since the `Update URI` header was added to WP and CP should have that, plugins checking other plugins for version compatibility.

**Comment by TukuToi** [comment]
The issue with duplicated plugins seems solved.
Theme check also seems to work, at least, when it is declared in the stylesheet - not when it is declared in the readme text file.
Response is:
`We cannot  that where true, then all plugins that do not feature the `Requires at least:` in the plugin header, now would not show that information anymore, correct?

@joyously - I am sure I miss something, but if you actually check the existing plugins, only a _few_ plugins do feature the data in the plugin header (close to none), as we discussed ad-absurdum already above. 
And they do _still show the data on WP Org repo_, just fine. 
So WP Did not drop anything, it seems. They added, but did not drop, as was explained in the Plugin Review channel as well. 
Clearly, they still read the readme (there's thousands of plugins not having a tad information in plugin main file and still showing the data on the worg entry of their plugin).
If you mean on a site install, then I am not sure how that will help us, again, because again plugins _do not include that data in the main file_. Only _few plugins_ do that.

Concluding - if we wasn't a holistic as possible check, and not label automatically 49.999k plugins as incompatible, we need to scan _both_, readme _and_ main file.

**Comment by joyously** [comment]
> I am sure I miss something

What you are missing is that no one is arguing about it but you.
> they do still show the data on WP Org repo, just fine.

Yes, the repo (which is the API) uses the readme. Period. Core does not (as of 5.8). Period.

> because again plugins do not include that data in the main file.

I don't know if the WP update API is separate from the rest of the WP repo API.

**Comment by TukuToi** [comment]
I am not arguing. I am stating since the begin of this thread we need A and B and you keep saying A and B are not true/not needed/not precise.

This doe snot contribute to make the thing happen, it only adds to the confusion as of _why_ it even has to happen.
Nice that we can agree that it _is required for our goal_

That is all we need to know, I think.

**Comment by mattyrob** [comment]
I've been trying to work through the minefield of all of the different places and ways the plugin or theme headers and readme files are parsed to get my head around this.

So, WordPress reads some data to display information on the plugins page for example, but there have been changes iterates since ClassicPress forked and therefore we cannot rely on these functions as they may not be identical in all of the WordPress versions we support migrating from.

ClassicPress includes the WordPress functions as forked at 4.9, we could update these but that is a ticket for consideration in the core repository IMO.

The WordPress API parses data to display in the plugin and theme repository, however it seems they are using not only core functions but also a plugin with extended functionality. See here:
https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/plugin-directory/class-readme-parser.php?rev=3473

So, the only way forward is to create our own checks in the migration plugin as relying on checks elsewhere will be inconsistent in terms of relying on functions or will result in multiple API calls and that may be incredibly slow.

**Comment by joyously** [comment]
> you keep saying A and B are not true/not needed/not precise.

I'm just trying to keep the facts in the forefront, not saying what is needed.
> I've been trying to work through the minefield of all of the different places and ways the plugin or theme headers and readme files are parsed

It's not a lot of places. The meta code you pointed to is executed when a new version of a plugin is committed to the WP repo. This is stored in the .org database, and retrieved by the WP API. Core WP does not parse the readme and only versions 5.5 to 5.7 used the two fields in the readme as a fallback for auto-updates, which would only affect plugins in the WP repo. Not only did 5.8 remove the readme fallback, it added support for `Update URI` so that external plugins could use the core logic to update the plugin. Core WP does extract the fields from the plugin header or theme style, though. Core WP calls the WP API for the Add New Plugin admin page, and for updates. For themes, it's in the Add New Theme and in the Customizer for installing themes. For showing installed plugins and themes, the info comes from the headers (not the readme).

Thanks for the reminder that the migration plugin runs under WP first, and then CP. But keep in mind that a site can have plugins from the WP repo, external repo, or custom made, and they might not have the correct fields in the header(written before field was added) or the readme (especially since the readme is only good for WP repo). 
_I don't think anyone is advocating calling WP API since it would not cover all cases._

**Comment by mattyrob** [comment]
I was referring not only yo the locations where require WP versions are pulled from in WordPress, but where they are stored in an API, where plugin and theme authors may put them and where they are secondarily stored in another API.

However, shall we try to get this ticket moving in a more constructive direction.

1. Is it generally agreed that creating and maintaining a list of conflicting plugins and themes could be a lot of work in the future?
2. Is it generally agreed that scanning a site before migration to assess if the migration is likely to go smoothly is a good idea?
3. Is it generally agreed that we may enhance the current code by scanning plugin and theme files and warning potential migrators if the current theme and any active plugins either declare that they need a specific version of WordPress that may therefore infer use of functions not in ClassicPress?
4. Is it generally agreed that we may enhance the current code by scanning plugin and theme files and warning potential migrators if the current theme and any active plugins fail to declare a supported version of WordPress at all?
