### ISSUE TITLE
Release includes a /lib/python folder.

### ISSUE THREAD

**Issue by TukuToi** [ClassicPress/ClassicPress-Migration-Plugin#78]
https://slack-files.com/TCD2YGSV9-F02AA9HBQA1-f38df84cdb

This is what I have in the Plugin folders when I download latest release

@striebwj or @mattyrob do you have chance to rebuild the release folder and reupload it without the python thingy?

**Comment by TukuToi** [comment]
James asks to:
>[...]this should be done as a new release rather than replacing an existing release

**Comment by striebwj** [comment]
Ya it should be, interesting that is did that. Will take a look

**Comment by mattyrob** [comment]
Dropping that folder could go into a 1.3.1 release and then we can look to release a 1.4.0 in the not to distant future with plugin header checking added along with the theme header checking which there is already a patch for.
