### ISSUE TITLE
Add conflicting plugins to the remote repo

### ISSUE THREAD

**Issue by TukuToi** [ClassicPress/ClassicPress-Migration-Plugin#80]
Let me know if this should go to another git project.

Here's the slugs of plugins I know from experience aren't working with ClassicPress and do not support WP 4.9 anymore:
**Toolset**
_Reason_: https://toolset.com/toolset-requirements/
`wp-views/wp-views.php`
`types/wpcf.php`
`cred-frontend-editor/plugin.php`
`types-access/types-access.php`
`toolset-blocks/wp-views.php`
`toolset-maps/toolset-maps-loader.php`
`woocommerce-views/views-woocommerce.php`
`cred-commerce/plugin.php`
**Elementor**
_Reason_: https://elementor.com/help/requirements/ 
I don't have the slugs for that plugin, as it is PRO, I only have the free slug:
`elementor/elementor.php`

Themes
**Kadence**
`kadence`
**Astra**
`astra`

**Comment by mattyrob** [comment]
I've created a PR in the API repository for the above changes.

**Comment by nylen** [comment]
Fixed in https://github.com/ClassicPress/ClassicPress-APIs/pull/26.
