### ISSUE TITLE
Core file differences reported if wp-config-sample.php missing

### ISSUE THREAD

**Issue by mattyrob** [ClassicPress/ClassicPress-Migration-Plugin#95]
As reported on Slack, if the `wp-config-sample.php` file is missing then core file differences are reported.

We might want to consider skipping this single file when reporting core file changes prior to migration.

<img width="1301" alt="Screenshot 2021-12-12 at 10 54 58" src="https://user-images.githubusercontent.com/1280733/145709559-53e0e54a-9d5b-4a8f-82ed-2193cb4c65f0.png">

**Comment by KTS915** [comment]
Fixed by PR #96
